name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and push docker image (AMD64)
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: bitt3r/monopoly
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  build-arm64:
    runs-on: ubuntu-latest
    container:
      image: tonistiigi/buildx:latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 14
        uses: actions/setup-java@v3
        with:
          java-version: '14'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and push docker image (ARM64)
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: bitt3r/monopoly
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          buildx-args: --platform=linux/arm64
