name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-amd64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17 (AMD64)
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and push docker image (AMD64)
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
          image: bitt3r/monopoly
          tag: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  setup-buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

  build-arm64:
    needs: setup-buildx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17 (ARM64) and Maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          maven-version: 'default'

      - name: Run tests with Maven
        run: mvn -B test --file pom.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Build and push docker image (ARM64)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bitt3r/monopoly:arm64-latest
          platforms: linux/arm64
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}