name: Test, Build and Publish Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'
          cache: maven

      - name: Test
        run: mvn -B test --file pom.xml

  build-windows:
    needs: test
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Build Docker image for Windows
        run: |
          docker build --build-arg JAR_FILE=target/monopoly.jar -t bitt3r/monopoly:windows-latest .

  build-ubuntu:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v2
        with:
          java-version: '14'
          distribution: 'adopt'

      - name: Build Docker image for Ubuntu
        run: |
          docker build --build-arg JAR_FILE=target/monopoly.jar -t bitt3r/monopoly:ubuntu-latest .

  push-windows:
    needs: build-windows
    runs-on: windows-latest
    steps:
      - name: Push Docker image for Windows
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bitt3r/monopoly:windows-latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  push-ubuntu:
    needs: build-ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Push Docker image for Ubuntu
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: bitt3r/monopoly:ubuntu-latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
